desktop = "hyprland"
tuning_profile = "gaming"

[locale]
locale = "en_US.UTF-8"
keymap = "us"
timezone = "America/New_York"

[disk]
disk = "/dev/vda"
filesystem = "zfs"


[disk.scheme]
type = "guided"

[disk.swap]
type = "zram"

[boot]
loader = "systemd-boot"
dual_boot = false
legacy_bios = false

[hardware]
arch = "x86_64-linux"
cpu = "intel"
gpu = ["nvidia-proprietary"]
firmware = "auto"

[network]
hostname = "hyprland-cachyos-bore-zfs"
host_id = "8425e349"
backend = "network-manager"

[kernel]
type = "cachy-os"
variant = "bore"
nixpkgs_policy = "pinned"


[accounts]
root_enabled = true
root_hashed_password = "$6$rvLVnhCHCaTgWmGH$xJvRfxD3tKxGIOKtyyJrz14ZxDJZ1BWoqTQBpwb7DAyZeGkT8F.HQoOwvQLnkmXmHnkH3V0k6h8AnqZmvHSsF."

[accounts.primary]
username = "balsa"
full_name = "Balsa Test User"
hashed_password = "$6$rvLVnhCHCaTgWmGH$xJvRfxD3tKxGIOKtyyJrz14ZxDJZ1BWoqTQBpwb7DAyZeGkT8F.HQoOwvQLnkmXmHnkH3V0k6h8AnqZmvHSsF."
