desktop = "plasma"
tuning_profile = "standard"
login_manager = "plasma-login-manager"

[locale]
locale = "en_US.UTF-8"
keymap = "us"
timezone = "America/New_York"

[disk]
disk = "/dev/vda"
filesystem = "btrfs"

[disk.scheme]
type = "guided"

[disk.swap]
type = "zram"

[boot]
loader = "systemd-boot"
dual_boot = false
legacy_bios = false

[hardware]
arch = "aarch64-linux"
cpu = "other"
gpu = ["virtio"]
firmware = "auto"

[network]
hostname = "plasma-lts-aarch64-zram"
backend = "network-manager"

[kernel]
type = "lts"


[accounts]
root_enabled = false

[accounts.primary]
username = "balsa"
full_name = "Balsa Test User"
hashed_password = "$6$rvLVnhCHCaTgWmGH$xJvRfxD3tKxGIOKtyyJrz14ZxDJZ1BWoqTQBpwb7DAyZeGkT8F.HQoOwvQLnkmXmHnkH3V0k6h8AnqZmvHSsF."
